var a = "welcome to node js it is the frost vodeo of the got hub voffo learned";

console.log(a);

const handleCalculate = (val1, val2) => {
  let add = val1 + val2;
  console.log(add, "add to number");
  let subs = val1 - val2;
  console.log(add, "subs to number");
  let divide = val1 / val2;
  console.log(add, "divide to number");
let multiply = val1 * val2 
console.log(multiply, "multiply two number")
};

handleCalculate(30, 05);


const haandleEmiCalculater =  (principalAmt,percentage) => {
            let result  = (principalAmt * percentage)/12
            console.log(result,"result permonth")
}
haandleEmiCalculater(12000,34)